MAPPING = {
    "Alachua CSO, Department of the Jail": 6830,
    "Alachua County Work Release": None,
    "Baker County Detention Center": 6832,
    "Bay County Jail and Annex": 6923,
    "Bradford County Jail": 6833,
    "Brevard County Detention Center": 6834,
    "Broward County Jail/Main": 6837,
    "Broward County Jail/North Broward": 6839,
    "Broward County Rein Facility": 6836,
    "Broward Conte Facility": 6835,
    "Calhoun County Jail": 6840,
    "Charlotte County Jail": 6841,
    "Citrus County Detention Center": 6925,
    "Clay County Jail": 6842,
    "Collier County Naples/Main": 6844,
    "Collier County/Immokalee Jail Center": 6843,
    "Columbia County Jail": 6845,
    "DeSoto County Jail": 6852,
    "Dixie County Jail": 6853,
    "Duval County Jail": 6920,
    "Escambia County Road Prison": 9825,
    "Escambia County Central Booking": 6854,
    "Flagler County Jail": 6856,
    "Franklin County Jail": 6857,
    "Gadsden County Jail": None,
    "Gilchrist County Jail": 6859,
    "Glades County Jail": 6860,
    "Gulf County Jail": 6861,
    "Hamilton County Jail": 6862,
    "Hardee County Jail": 6863,
    "Hendry County Jail": 6864,
    "Hernando County Jail": 6926,
    "Highlands County Jail": 6865,
    "Hillsborough County/Orient Road": 6867,
    "Hillsborough County/Falkenburg Rd.": 6866,
    "Holmes County Jail": 6868,
    "Indian River County Jail": 6869,
    "Jackson County Jail": 6870,
    "Jefferson County Jail": 6871,
    "Lafayette County Jail": None,
    "Lake County Jail": 6873,
    "Lee County Jail/Main": 6877,
    "Lee County Jail/Ortiz": 6876,
    "Leon County Jail": 6878,
    "Levy County Jail": 6879,
    "Liberty County Jail": 6880,
    "Madison County Jail": 6881,
    "Marion County Jail": 6883,
    "Martin County Jail": 6884,
    "Miami-Dade County Jail/Main PTDC": 6850,
    "Miami-Dade County Jail/MWDC": 6847,
    "Miami-Dade County Jail/TGK": 6851,
    "Miami-Dade County Boot Camp": 6846,
    "Monroe County Jail/Main": 6887,
    "Monroe County/Plantation Key": 6885,
    "Nassau County Jail": 6888,
    "Okaloosa County Jail": 6889,
    "Okeechobee County Jail": 6890,
    "Orange County/33rd Street": None,
    "Orange County/Juvenile Assessment": None,
    "Osceola County Jail": 6894,
    "Palm Beach County/Main": 6896,
    "Palm Beach County/West County": 6895,
    "Pasco County/Land O'Lakes": 6898,
    "Pinellas County Detention and Corrections": 9777,
    "Polk Central County Jail": None,
    "Polk County South County Jail": None,
    "Putnam County Jail": 6905,
    "St. Johns County Jail**": 6906,
    "St. Johns County Jail": 6906,  # just in case
    "St. Johns County Work Release": 9607,
    "St. Lucie County Corr. Facility": 6907,
    "Santa Rosa County Jail": 6908,
    "Sarasota County Jail": 6909,
    "Seminole County Jail": 6910,
    "Sumter County Jail": 6911,
    "Suwannee County Jail": 6912,
    "Taylor County Jail": 6913,
    "Union County Jail": 6914,
    "Volusia County Corr. Facility": 6915,
    "Volusia County/Branch Jail": 6916,
    "Wakulla County Jail": 6917,
    "Walton County Jail": 6918,
    "Washington County Jail": 6919,
}